name = "iframely"
main = "src/index.ts"
compatibility_date = "2023-01-25"
keep_vars = true

routes = [
	{ pattern = "iframely.lenster.xyz", custom_domain = true }
]

[[r2_buckets]]
binding = 'LENSTER_IFRAMELY'
bucket_name = 'lenster-iframely'
preview_bucket_name = 'lenster-iframely'

[env.production.vars]
IFRAMELY_API_KEY = ""
