name = "iframely"
main = "src/index.ts"
compatibility_date = "2023-01-25"
keep_vars = true

routes = [
	{ pattern = "iframely.lenster.xyz", custom_domain = true }
]

kv_namespaces = [
  { binding = "LENSTER_IFRAMELY", id = "f163e4a9a3a742d4bc6f3713b2959e2e", preview_id = "f163e4a9a3a742d4bc6f3713b2959e2e" }
]

[env.production.vars]
IFRAMELY_API_KEY = ""
