version: 2
updates:
  - package-ecosystem: 'pnpm'
    directory: '/apps/web'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/apps/prerender'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/abis'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/bundlr'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/config'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/data'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/image-cropper'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/lens'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/lib'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/snapshot'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/types'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/workers/achievements'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/workers/ens'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/workers/freshdesk'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/workers/invite'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/workers/ipfs'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/workers/leafwatch'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/workers/metadata'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/workers/oembed'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/workers/prerender'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/workers/snapshot-relay'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pnpm'
    directory: '/packages/workers/sts-generator'
    schedule:
      interval: 'daily'
