version = 1

exclude_patterns = [
  "node_modules",
  ".next",
  ".github",
  ".husky",
  ".vscode",
  "pnpm-lock.yaml",
  "packages/lens/generated.ts",
  "packages/workers/snapshot-relay/generated.ts",
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "prettier"
enabled = true
