tasks:
  - init: |
      nvm i 14
      nvm use 14
      nvm alias default  14
      echo "nvm use default &>/dev/null" >> ~/.bashrc.d/51-nvm-fix
      yarn install
    command: yarn dev

ports:
  - port: 4783 # Web app
    visibility: public
    onOpen: notify
