include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml

housekeeping:
  before_script: []
  script:
    - curl --request POST --header "PRIVATE-TOKEN:$ACCESS_TOKEN" https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/housekeeping
  only:
    - main
