image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup
    init: |
      yarn install
      yarn codegen
      cp .env.example .env
    command: yarn dev

  - command: |
      clear
      echo "Waiting for server to start 🕒"
      gp await-port 4783
      scripts/gp-welcome.sh

ports:
  - port: 4783 # Web app
    visibility: public
    onOpen: notify

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - wix.vscode-import-cost
    - formulahendry.auto-close-tag
    - bradlc.vscode-tailwindcss
    - pkief.material-icon-theme
