name = "freshdesk"
main = "src/index.ts"
compatibility_date = "2023-01-25"
routes = [
	{ pattern = "freshdesk.lenster.xyz", custom_domain = true }
]
keep_vars = true

[env.production.vars]
POSTMARK_TOKEN = ""
