name = "leafwatch-worker"
main = "src/index.ts"
compatibility_date = "2023-01-25"
logpush = true
routes = [
	{ pattern = "leafwatch.lenster.xyz", custom_domain = true }
]
keep_vars = true

[env.production.vars]
DATADOG_TOKEN = ""
