name: "Bug Report"
description: 'Report a reproducible bug in the Lenster'
labels: 'needs review'
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: markdown
    attributes:
      value: If you leave out sections there is a high likelihood your issue will be closed.
  - type: textarea
    attributes:
      label: Summary
      description: Describe the issue in 1 or 2 sentences
      placeholder: Clearly describe what the expected behavior is vs. what is actually happening.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What platform(s) does this occur on?
      multiple: true
      options:
        - Android
        - iOS
        - Web
    validations:
      required: true
