name = "raven"
main = "src/index.ts"
compatibility_date = "2023-01-25"
keep_vars = true

routes = [
	{ pattern = "raven.lenster.xyz", custom_domain = true }
]

[env.production.vars]
DATADOG_TOKEN = ""
