name = "access"
main = "src/index.ts"
compatibility_date = "2023-01-25"
keep_vars = true
node_compat = true

routes = [
	{ pattern = "access.lenster.xyz", custom_domain = true }
]

kv_namespaces = [
  { binding = "ACCESS", id = "52cc9d21444249fc81a6c340f6ca6251", preview_id = "52cc9d21444249fc81a6c340f6ca6251" }
]

[env.production.vars]
SUPABASE_KEY = ""
