name: Analyze Bundle

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Restore next build
        uses: actions/cache@v3
        id: restore-build-cache
        env:
          cache-name: cache-next-build
        with:
          path: .next/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Build next.js app
        run: yarn build
        env:
          SENTRY_AUTH_TOKEN: '${{ secrets.SENTRY_AUTH_TOKEN }}'

      - name: Analyze bundle
        run: npx -p nextjs-bundle-analysis report

      - name: Upload bundle
        uses: actions/upload-artifact@v2
        with:
          path: .next/analyze/__bundle_analysis.json
          name: bundle_analysis.json

      - name: Download base branch bundle stats
        uses: dawidd6/action-download-artifact@v2
        if: success() && github.event.number
        with:
          workflow: analyze.yml
          branch: ${{ github.event.pull_request.base.ref }}
          name: bundle_analysis.json
          path: .next/analyze/base/bundle

      - name: Compare with base branch bundle
        if: success() && github.event.number
        run: ls -laR .next/analyze/base && npx -p nextjs-bundle-analysis compare

      - name: Upload analysis comment
        uses: actions/upload-artifact@v2
        with:
          name: analysis_comment.txt
          path: .next/analyze/__bundle_analysis_comment.txt

      - name: Save PR number
        run: echo ${{ github.event.number }} > ./pr_number

      - name: Upload PR number
        uses: actions/upload-artifact@v2
        with:
          name: pr_number
          path: ./pr_number
