name: Chore Issue

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  create:
    name: Create
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v3

      - name: Create Issue 📝
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/chore-issue.md
