name: Crowdin upload

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  upload-translations:
    name: Upload translations
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🚪
      uses: actions/checkout@v3

    - name: Upload to Crowdin ⬆️
      uses: crowdin/github-action@1.5.2
      with:
        upload_translations: true
        download_translations: false
        project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
        token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        source: '/**/locales/en/*.po'
        translation: '/**/locales/%two_letters_code%/%original_file_name%'
