name: Dependency Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  dependency-review:
    name: Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v3

      - name: Dependency Review 📝
        uses: actions/dependency-review-action@v3
