name: Deploy cloudflare workers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v3

      - name: Check for changes 📝
        id: check
        uses: dorny/paths-filter@v2
        with:
          filters: |
            changed:
              - 'packages/workers/**'

      - name: Cancel workflow if there are no changes 🚫
        if: steps.check.outputs.changed == 'false'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.actions.cancelWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            })

      - name: Setup pnpm 🌸
        uses: pnpm/action-setup@v2.2.4

      - name: Setup node 🍀
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install 📦
        run: pnpm install --frozen-lockfile

      - name: Deploy 🚀
        run: |
          pnpm add wrangler -g
          pnpm workers:deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
