name: Deploy cloudflare workers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm 🌸
        uses: pnpm/action-setup@v2.2.4

      - name: Setup node 🍀
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install 📦
        run: pnpm install --frozen-lockfile

      - name: Deploy 🚀
        run: |
          pnpm add wrangler -g
          pnpm workers:deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
