name: Lint / Prettier checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 15.x
          cache: 'yarn'

      - name: Install dependencies
        run: npm ci

      - name: Lint codebase
        run: npm run lint

  prettier:
    runs-on: ubuntu-latest
    name: Prettier
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 15.x
          cache: 'yarn'

      - name: Install dependencies
        run: npm ci

      - name: Lint codebase
        run: npm run prettier:check
