name: Push SNS Docker Image

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'packages/sns/**'

jobs:
  push:
    name: Push SNS Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: Bhacaz/checkout-files@v2
        with:
          files: packages/sns
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: packages/sns
          file: packages/sns/Dockerfile
          push: true
          tags: yoginth/sns:latest
