name: Release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.LENSTER_BOT_GH_TOKEN }}

      - name: Testnet
        run: ./script/release testnet

      - name: Staging
        run: ./script/release staging

      - name: Sandbox
        run: ./script/release sandbox

      - name: Staging Sandbox
        run: ./script/release staging-sandbox
