name: Sync Testnet

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'testnet'
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin main
          git push origin testnet
