name: Git Repo Sync

on:
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync
    steps:
    - name: Checkout 🚪
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: GitLab 🦊
      uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        target-url: ${{ vars.GITLAB_URL }}
        target-username: ${{ vars.GITLAB_USERNAME }}
        target-token: ${{ secrets.GITLAB_SYNC_TOKEN }}
