name: Git Repo Sync

on:
  push:
    branches: [main, testnet, sandbox, staging, staging-sandbox]

jobs:
  gitlab:
    runs-on: ubuntu-latest
    name: Sync to GitLab
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push
        uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: ${{ vars.GITLAB_URL }}
          target-username: ${{ vars.GITLAB_USERNAME }}
          target-token: ${{ secrets.GITLAB_SYNC_TOKEN }}

  codecommit:
    runs-on: ubuntu-latest
    name: Sync to AWS CodeCommit
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push
        uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: ${{ vars.CODECOMMIT_URL }}
          target-username: ${{ vars.CODECOMMIT_USERNAME }}
          target-token: ${{ secrets.CODECOMMIT_SYNC_TOKEN }}

  codegiant:
    runs-on: ubuntu-latest
    name: Sync to Codegiant
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push
        uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: ${{ vars.CODEGIANT_URL }}
          target-username: ${{ vars.CODEGIANT_USERNAME }}
          target-token: ${{ secrets.CODEGIANT_SYNC_TOKEN }}

  azure-devops:
    runs-on: ubuntu-latest
    name: Sync to Azure DevOps
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push
        uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: ${{ vars.AZURE_DEVOPS_URL }}
          target-username: ${{ vars.AZURE_DEVOPS_USERNAME }}
          target-token: ${{ secrets.AZURE_DEVOPS_SYNC_TOKEN }}
