name: Update dependency task

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  create_task:
    name: Create task
    runs-on: ubuntu-latest
    steps:
      - name: Create task ➕
        uses: korosuke613/linear-app-create-issue-action@v1
        with:
          issueFilePath: "../update-deps.md"
          apiKey: ${{ secrets.LINEAR_API_TOKEN }}
          teamId: ${{ secrets.LINEAR_TEAMID }}
          stateId: ${{ secrets.LINEAR_STATEID }}
