name: Verify Profiles

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  verify:
    name: Verify Profiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BIGINT_GH_TOKEN }}

      - name: Setup node 🍀
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Run script 📜
        run: node packages/data/verify-profiles.js

      - name: Commit & Push changes 📤
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.BIGINT_GH_TOKEN }}
          force: true
